I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 327, in script
    eslow "..."
Exception: Sayer 'eslow' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 327, in script
    eslow "..."
  File "C:\Users\jgonzale5\Downloads\renpy-6.99.11-sdk\renpy\ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\jgonzale5\Downloads\renpy-6.99.11-sdk\renpy\ast.py", line 500, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'eslow' is not defined.

Windows-8-6.2.9200
Ren'Py 6.99.11.1749
Rigged Heart 1.0
